version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/spring-graphql"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "rajadilipkolli"
    assignees:
      - "rajadilipkolli"
    labels:
      - "dependencies"

  - package-ecosystem: "gradle"
    directory: "/spring-graphql-querydsl"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "rajadilipkolli"
    assignees:
      - "rajadilipkolli"
    labels:
      - "dependencies"

  - package-ecosystem: "gradle"
    directory: "/strategy-plugin"
    schedule:
      interval: weekly
    reviewers:
      - "rajadilipkolli"
    assignees:
      - "rajadilipkolli"
    labels:
      - "dependencies"