"component : archunit":
 - boot-api-archunit-sample/**/*
"component : choas-monkey":
 - spring-boot-choas-monkey/**/*
"component: graphql-webflux":
  - graphql/spring-boot-graphql-webflux/**/*
"component: graphql-webmvc":
  - graphql/spring-boot-graphql-webmvc/**/*
"component: graphql-querydsl":
  - graphql/spring-boot-graphql-querydsl/**/*
"component: hibernate2ndlevelcache-sample":
  - jpa/boot-hibernate2ndlevelcache-sample/**/*
"component: jobrunr":
  - boot-jobrunr-sample/**/*
"component: data-envers":
  - jpa/boot-data-envers/**/*
"component: jpa-multitenancy":
  - jpa/multitenancy/**/*
"component: multiple-datasources":
  - jpa/boot-data-multipledatasources/**/*
"component: read-replica-postgres":
  - jpa/boot-read-replica-postgresql/**/*
"component: customsequence":
 - jpa/boot-data-customsequence/**/*
"component: mongodb-elasticsearch":
  - boot-mongodb-elasticsearch/**/*
"component: strategy-plugin":
  - boot-strategy-plugin/**/*
"component: togglz":
  - spring-boot-togglz-sample/**/*
"component: ultimate-redis":
  - boot-ultimate-redis/**/*
"component: rabbitmq-thymeleaf":
  - boot-rabbitmq-thymeleaf/**/*
"component: r2dbc":
  - r2dbc/boot-jooq-r2dbc-sample/**/*
"component: openapi":
  - open-api-spring-boot/**/*
"component: httpclients":
  - httpClients/web-client-webflux/**/*
  - httpClients/http-proxy/**/*
  - httpClients/rest-template/**/*
  - httpClients/web-client-mvc/**/*
"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*
"type: dependency-upgrade":
  - boot-api-archunit-sample/pom.xml
  - spring-boot-choas-monkey/pom.xml
  - jpa/boot-data-envers/build.gradle
  - jpa/boot-hibernate2ndlevelcache-sample/pom.xml
  - jpa/multitenancy/multitenancy-db/pom.xml
  - jpa/multitenancy/multidatasource-multitenancy/pom.xml
  - jpa/multitenancy/partition/pom.xml
  - jpa/multitenancy/schema/pom.xml
  - jpa/boot-data-multipledatasources/pom.xml
  - jpa/boot-read-replica-postgresql/pom.xml
  - jpa/boot-data-customsequence/pom.xml
  - boot-jobrunr-sample/pom.xml
  - boot-mongodb-elasticsearch/pom.xml
  - graphql/spring-boot-graphql-webflux/build.gradle.kts
  - graphql/spring-boot-graphql-querydsl/build.gradle.kts
  - graphql/spring-boot-graphql-webmvc/pom.xml
  - boot-strategy-plugin/build.gradle
  - spring-boot-togglz-sample/pom.xml
  - boot-ultimate-redis/pom.xml
  - boot-rabbitmq-thymeleaf/pom.xml
  - r2dbc/boot-jooq-r2dbc-sample/pom.xml
  - httpClients/http-proxy/pom.xml
  - httpClients/rest-template/pom.xml
  - httpClients/web-client-webmvc/pom.xml
  - httpClients/web-client-webflux/pom.xml
  - open-api-spring-boot/pom.xml
