version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:21-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=rajadilipkolli_my-spring-boot-experiments

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud