version: '3.8'
services:

  boot-opensearch-sample:
    build: ..
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - opensearch
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENSEARCH_URIS=http://opensearch:9200
