version: "3.8"
services:
    tempo:
        image: grafana/tempo
        extra_hosts: ['host.docker.internal:host-gateway']
        container_name: tempo
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - ./docker/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
            - ./docker/tempo/tempo-data:/tmp/tempo
        ports:
            - "3110:3100"     # Tempo
            - "4317:4317"     # OTLP
            - "9411:9411"     # Zipkin

    loki:
        image: grafana/loki
        extra_hosts: ['host.docker.internal:host-gateway']
        container_name: loki
        command: [ "-config.file=/etc/loki/local-config.yaml" ]
        ports:
            - "3100:3100"                                   # loki needs to be exposed so it receives logs

    prometheus:
        image: prom/prometheus
        extra_hosts: ['host.docker.internal:host-gateway']
        container_name: prometheus
        command:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-remote-write-receiver
        volumes:
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana
        extra_hosts: ['host.docker.internal:host-gateway']
        container_name: grafana
        depends_on:
            - loki
            - prometheus
            - tempo
        volumes:
            - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
            - ./docker/grafana/provisioning/grafana.ini:/etc/grafana/grafana.ini
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"
