name: CI Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: batch-boot-jpa
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean verify
